language: php
os: linux

jobs:
  include:
    - php: 5.6
    - php: 5.6
    - php: 7.0
    - php: 7.0
    - php: 7.1
    - php: 7.1
    - php: 7.2
    - php: 7.2
    - php: 7.3
    - php: 7.3
    - php: 7.4
    - php: 7.4

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - composer install -n

script:
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs src tests --standard=psr2 -sp

after_script:
  - php vendor/bin/coveralls
